# Generated by Django 4.1.5 on 2023-01-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
