# Generated by Django 4.1.5 on 2023-02-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_image',
        ),
    ]
