# Generated by Django 4.1.5 on 2023-01-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='image',
            new_name='banner_image',
        ),
    ]
