# Generated by Django 4.1.5 on 2023-01-21 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_bannermodel_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
