# Generated by Django 4.1.5 on 2023-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='size',
            field=models.CharField(max_length=8),
        ),
    ]
